language: "python"
python: "3.6"
sudo: required
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
install: "pip install flake8"
script:
  - test/static_code_analysis.sh
  - yes "" | ./pmbootstrap.py init
  - test/check_checksums.py
notifications:
  - email: false
