#!/sbin/ash -e
# shellcheck source=pmos_install_functions
. /tmp/postmarketos/bin/pmos_install_functions

extract_partition_table
set_subpartitions
echo "Set the password of the encrypted rootfs!"
set_password
#Remove temporary keyfile
cryptsetup luksRemoveKey "$ROOT_PARTITION" "$WORKING_DIR"/lukskey
echo "Successfully added key to the LUKS device."
