#!/sbin/sh
. /tmp/postmarketos/bin/pmos_install_functions

extract_partition_table
set_subpartitions
set_password
#Remove temporary keyfile
cryptsetup luksRemoveKey "$ROOT_PARTITION" "$WORKING_DIR"/lukskey
