#!/sbin/ash
# shellcheck source=pmos_install_functions
. /tmp/postmarketos/bin/pmos_install_functions "$1" "$2"
# shellcheck source=/dev/null
. "$WORKING_DIR"/install_options

exec > "$WORKING_DIR"/pmos.log 2>&1
set -ex

ui_print "postmarketOS recovery installer"

ui_print "Extracting partition info from fstab..."
extract_partition_table
ui_print "Entering working directory..."
cd "$WORKING_DIR"
ui_print "Extracting files..."
unzip -o "$ZIP"
mkdir /lib
ui_print "Symlinking .so files to /lib/..."
ln -s "$WORKING_DIR"/lib/* /lib/
ui_print "Unmounting /$INSTALL_PARTITION..."
umount_install_partition
ui_print "Creating partition table on $INSTALL_DEVICE..."
partition_install_device
if [ "$FDE" = "true" ]
then
	ui_print "Generating temporary keyfile with random data..."
	dd bs=512 count=4 if=/dev/urandom of="$WORKING_DIR"/lukskey
	ui_print "Initializing LUKS device..."
	cryptsetup luksFormat --use-urandom -c "$CIPHER" -q "$ROOT_PARTITION" "$WORKING_DIR"/lukskey
	ui_print "Opening LUKS partition..."
	cryptsetup luksOpen -d "$WORKING_DIR"/lukskey "$ROOT_PARTITION" pm_crypt
	ui_print "Formatting LUKS partition..."
	make_ext4fs -L 'pmOS_root' /dev/mapper/pm_crypt
	ui_print "Mounting LUKS partition..."
	mount -t ext4 -rw /dev/mapper/pm_crypt /"$INSTALL_PARTITION"
else
	ui_print "Formatting root partition..."
	make_ext4fs -L 'pmOS_root' "$ROOT_PARTITION"
	ui_print "Mounting root partition..."
	mount -t ext4 -rw "$ROOT_PARTITION" /"$INSTALL_PARTITION"
fi
ui_print "Formatting pmOS_boot..."
mkfs.ext2 -q -L 'pmOS_boot' "$PMOS_BOOT"
ui_print "Mounting pmOS_boot..."
mkdir /"$INSTALL_PARTITION"/boot
mount -t ext2 -rw "$PMOS_BOOT" /"$INSTALL_PARTITION"/boot
ui_print "Installing rootfs..."
tar -xf rootfs.tar.gz -C /"$INSTALL_PARTITION"
if [ "$FLASH_BOOTIMG" = "true" ]
then
	ui_print "Flashing boot.img..."
	dd if=boot.img of="$BOOT"
fi
if [ "$FDE" = "true" ]
then
	ui_print "Creating a symlink for password setting script in /sbin/..."
	ln -s "$WORKING_DIR"/bin/pmos_setpw /sbin/
	ui_print "Do not forget to add a password to the LUKS partition!"
	ui_print "Run the command: pmos_setpw from the terminal/adb shell!"
fi
ui_print "Installation done."
