#!/sbin/sh
# Print fail information
OUTFD=$2
fail_info() {
	FAIL_MSG="Failed. Check $WORKING_DIR/pmos.log for more info!"
	echo -n -e "ui_print $FAIL_MSG\n" > /proc/self/fd/"$OUTFD"
	echo -n -e "ui_print\n" > /proc/self/fd/"$OUTFD"
}
# Create working directory
mkdir /tmp/postmarketos/
# Extract and start the installer script
unzip $3 "bin/pmos_install" "bin/pmos_install_functions" "install_options" -d /tmp/postmarketos/
/tmp/postmarketos/bin/pmos_install $2 $3 || { fail_info ; exit 1 ; }
